project:
  type: website
  output-dir: docs

website:
  title: "paulorssalves"
  navbar:
    right:
      - clinica.qmd
      - producoes.qmd
      - postagens.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

lang: pt 