---
title: Clínica
subtitle: Minha abordagem na psicoterapia
title-block-banner: true
---

Minhas influências na clínica são múltiplas. É comum que psicólogos perguntem uns aos outros "qual é sua linha?", querendo saber a diretriz teórica que os orienta. Durante a minha formação, ouvi um professor meu dizer, jocosamente, que era "desalinhado". Eu me identifiquei com isso.

Não quer dizer que não tenho uma orientação teórica para a clínica. O problema é que eu não consigo encontrar um lugar para recostar a cabeça. O campo da psicologia é todo muito interessante, e eu me enveredo por múltiplas escolas de investigação: psicanálise, psicologia existencial, psicologia existencial, esquizoanálise, gestalt terapia, psicometria, psicologia cognitiva...

Se eu fosse tentar resumir, diria que tenho um lado contemplativo que opera no fundo -- fortemente pautado por Deleuze, Guattari, Lacan, Jung, Freud, Heidegger -- e que me torna profundamente crítico com toda teoria que eu leio. Ao mesmo tempo, tenho ampla prática com métodos estatísticos em psicologia, e por meio destes eu fico nas margens da psicologia cognitiva. 

São abordagens que entram em choque. O que uma diz, a outra com frequência contradiz. É nesse jogo de tensões que eu faço a minha morada, e é com o incômodo da irredutibilidade que eu levo a minha prática clínica.