---
title: Moralismo é uma tentação
date: 2025-07-19
categories: ["psicopatologia"]
---

Para as pessoas que são parte de alguma categoria clínica de ordem psicopatológica (TDAH, depressão, ansiedade, bipolaridade etc.)[^1] pode talvez ser uma tentação apoiar-se no seu próprio status de categorizado. Isso é, "não sou eu, é o meu transtorno". Em muitos casos isso será verdadeiro, mas em outros será apenas uma desculpa, uma forma de ensaboadamente fugir de um problema e da própria responsabilidade.

[^1]: Tomemos essas categorias clínicas apenas como símbolos de conjuntos de sintomas que diferentes pessoas tendem a apresentar. Não pense que essas coisas são doenças em si; TDAH não é a doença, é o sintoma. O mesmo se aplica pra depressão, bipolaridade etc.

Muitas pessoas não gostam disso, entretanto. Parece-me que existe uma certa glamourização de alguns psicodiagnósticos, mas quem realmente sofre dessas coisas em sua maioria não gosta delas, e portanto não se orgulha e nem faz disso sua identidade. Há excessões, claro, mas mais me parece que quem orgulhosamente ostenta "ser" TDAH são os autodiagnosticados. Do mesmo modo, parece-me que quem sofre dessas coisas, quando se justifica por meio delas não o faz com um sentimento de malandragem, mas sim com pesar e lástima.

Mas se apoiar-se nos diagnósticos é uma tentação, do mesmo modo é tentador ceder ao desejo de ignorá-los e reduzir tudo a questões morais. "Não é sua psicopatologia, mas você que tem que tomar vergonha na cara."

Pessoas que sofrem de depressão, por exemplo, sofrem duplamente por causa desse tipo de julgamento. Depressão resulta em uma espécie de "abulia", que significa "ausência de vontade". Isso não quer dizer que a pessoa não quer nada, mas sim que ela não consegue exercer força de vontade em nenhuma direção. Pessoas "normais" conseguem se forçar a fazer coisas indesejáveis, enquanto os deprimidos não conseguem fazer nem as desejáveis, que dirá a que todos phderiam por evitar.

Pessoas com TDAH sofrem de problemas parecidos. Não é tanto uma abulia, mas o avesso do hiperfoco: conseguem se concentrar intensamente em um certo objeto de interesse, mas sofrem muito para dar atenção a algo menos chamativo. Isso não é um a dificuldade moral, falta de vergonha na cara, e a pessoa não tem que simplesmente "se forçar a fazer o que não quer."

Na realidade essa evitação de certas tarefas tem múltiplas facetas: uma é algo que pode ser fenomenologicamente percebido como uma "parede invisível", e outra é um problema na formação de categorias. Por exemplo, é comum que as pessoas "normais" consigam dizer onde uma tarefa começa e outra acaba; há uma capacidade para definir limites entre uma coisa e outra e separá-las. Algumas pessoas categorizadas com "TDAH" não tem esse tipo de habilidade, e isso dificulta a organização das ações em um plano (ou sua execução) ao longo do dia a dia.

Então veja bem. Por fora pode parecer preguiça e indiferença, mas por dentro o que existe é um misto de incapacidade com deficiência -- ambas, em grande parte dos casos, temporárias e tratáveis. Mas certamente não é "falta de vergonha na cara" ou coisa do tipo. Assim, sofrimento psíquico não é uma questão moral. Os que sofrem por estarem deprimidos, em geral, não vão resolver suas questões com força de vontade. Força de vontade, aliás, acaba sendo o falso remédio para a maioria dos tipos de sofrimentos psíquicos. Mas eles são tão diversos, e têm origens tão diferentes, que força de vontade só vai ser a solução pra um conjunto muito ínfimo de casos. Talvez nenhum.